### ISSUE TITLE
Relay docs

### ISSUE THREAD

**Issue by faddat** [akash-network/cosmos-omnibus#127]
Document how to use this to provide relay nodes. 

You can assign this to me.

**Comment by faddat** [comment]
# essay

Relayers require an ever growing set of nodes, which need to be configured for ideal performance.  

* rocksdb
* statesync

are likely the two most important tweaks.  

**goals**

For non-wasm chains, make sure that state sync is an easy option for users.

**Comment by tombeynon** [comment]
This would be awesome @faddat. I had a feeling Omnibus could be useful for relayers but I'm not running any myself just yet. We expose some configs to make statesync a bit easier, e.g. pulling trust height etc. Chain registry listing statesync rpc nodes could take this a bit further. Let me know if I can help with anything at all or if you want to chat through Omnibus sometime

**Comment by faddat** [comment]
Tom, I would love to have a chat.  

How do we link up?  Could you send me a twitter DM to @gadikian ?  I am meeting with Nick from Osmosis tomorrow on exactly this.

**Comment by tombeynon** [comment]
Closing as statesync is fully supported, and [v1.0.0](https://github.com/akash-network/cosmos-omnibus/releases/tag/v1.0.0) focussed on making Omnibus as easy to get running as possible
