### ISSUE TITLE
Fat Gaia

### ISSUE THREAD

**Issue by faddat** [akash-network/cosmos-omnibus#13]
The v4.2.1 config originally found here for gaia will work, and begin to sync.  The beginning of gaia's current state is compatible with those consensus rules.  Then, She will change over to v5.0.0 consensus rules, and the current binary is v5.0.2.  

In order to make fat gaia happy, you'll need to give her cake, which is available at quicksync.io

Gaia is very fat, and she is sure to get fatter.  

https://github.com/cosmos/gaia/issues/704

**Comment by tombeynon** [comment]
This is awesome and the first time I've come across quicksync.io. We'd need to make a minor update to handle the `tar.lz4` archives, and I can't see a way to list the available archives in a way we could pick the latest automatically. But even if this is just a section in the docs referring to quicksync and encourage people to pick their own, it's a great way to bootstrap nodes.
