### ISSUE TITLE
Validators

### ISSUE THREAD

**Issue by faddat** [akash-network/cosmos-omnibus#148]
Strongly held opinion:

Due to the fact that validators secure their chains and do so with cryptographic material, validator operation is best done from people's homes and offices, and automation is a - not a +.

**Comment by tombeynon** [comment]
Definitely agree with this, and I think it's something we don't market enough with Omnibus. It's obviously Akash ready but the biggest change is having standardised docker containers, i.e. extremely portable nodes. I run all my validator operations using Omnibus and being able to run an identical container at home vs in a data center vs office is really powerful and flexible. Would love to see how much further we can take this
