### ISSUE TITLE
List divergences

### ISSUE THREAD

**Issue by faddat** [akash-network/cosmos-omnibus#149]
https://github.com/ovrclk/cosmos-omnibus/blob/874a6b326c0fde9730936c53bf313c7c29ec4ad8/run.sh#L117

Social pressure can be very powerful.  Chains that don't support the seeds env var should be added to a list in the readme of the chain registry, just like open source chains or chains that only ever had one validator.

**Comment by tombeynon** [comment]
So the ENV variable config of tendermint chains is so unbelievably useful, and it's barely documented anywhere. From what I've seen almost all chains support the ENV var convention (the referenced line was added for Thorchain I believe, which is quite different), however finding the ENV var namespace is a challenge. I think this would be a great addition to chain-registry, and would then be a clear indicator if a chain didn't support the standard ENV var config.

In case it's not super obvious, the namespace for each chain is in the build.yml and README files for each project.

**Comment by faddat** [comment]
You are right Tom, the namespace is not always obvious, like when there is a _ in the name :)

**Comment by tombeynon** [comment]
Namespace is now configured automatically and always matches the binary name in uppercase
