### ISSUE TITLE
Add docs for project upgrades

### ISSUE THREAD

**Issue by JianHongHong** [akash-network/cosmos-omnibus#294]
Add in documentation for project upgrades procedure. For example: juno:v1.0.0 -> juno:v2.0.0

**Comment by tombeynon** [comment]
Agree this could be clearer, thanks for raising. The easiest solution is to use a snapshot (e.g. from Polkachu), or the Generic build outlined in the docs to step through the versions.

Will add a wiki when I can

**Comment by tombeynon** [comment]
There is a wiki here @JianHongHong, does this cover what you were looking for? https://github.com/akash-network/cosmos-omnibus/wiki/Chain-Upgrades

**Comment by JianHongHong** [comment]
Yes this is what I was looking for. Thanks!
