### ISSUE TITLE
snapshots: automatically detect directory structure

### ISSUE THREAD

**Issue by andy108369** [akash-network/cosmos-omnibus#378]
some snapshots have `data` and `wasm` directories, I think they should get automatically detected before the extraction.

they are currently getting set via these variables:

```
- SNAPSHOT_WASM_PATH=wasm
- SNAPSHOT_DATA_PATH=data
```

ref. https://github.com/ovrclk/cosmos-omnibus/issues/372

**Comment by tombeynon** [comment]
Agreed, should be easy enough to make this dynamic
