### ISSUE TITLE
Launching nodes seems broken? Osmosis and Cosmos

### ISSUE THREAD

**Issue by chokosabe** [akash-network/cosmos-omnibus#387]
Issues trying to get cosmos and osmosis nodes up and running using the cloudmos templates (via the app)

Osmosis node starts and then silently stops

Cosmos emits this message and then stops:

node: Issue obtaining the Polkachu snapshot. Likely the API issue.
node: Sleeping for 10 minutes before restarting...

**Comment by tombeynon** [comment]
Sadly Polkachu has disabled access to the API which returns snapshot URLs. This means we can't programatically find the latest snapshot using the `SNAPSHOT_POLKACHU=1` environment variable config. You will need to find the latest snapshot [on their website manually](https://polkachu.com/tendermint_snapshots/osmosis) and use the following config instead, replacing the URL with the one you wish to use:

```
SNAPSHOT_URL=https://snapshots.polkachu.com/snapshots/osmosis/osmosis_8285615.tar.lz4
SNAPSHOT_DATA_PATH=data
```
