### ISSUE TITLE
Bitcanna deployment crashes after max 10 minutes of running - image outdated

### ISSUE THREAD

**Issue by shimpa1** [akash-network/cosmos-omnibus#453]
Deploying a Bitcanna node on any provider causes it to crash after 3-10 minutes of running.

- Tested using 4 and 8 VCPU
- Tested using 8Gi, 16Gi and 32Gi of RAM
- Tested using 100Gi ephemeral storage
- Tested using 5Gi of ephemeral storage + 500Gi of persistent storage (beta2 and beta3)
- Tested on Europlots.com provider (ephemeral only and ephemeral+beta3) and boxedcloud.net provider (ephemeral+beta2)

These are the deployment events:

`[node]: [Normal] [Pulled] [Pod] Container image "ghcr.io/akash-network/cosmos-omnibus:v0.3.27-bitcanna-v1.5.3" already present on machine
[node]: [Normal] [Created] [Pod] Created container node
[node]: [Normal] [Started] [Pod] Started container node
[node]: [Warning] [BackOff] [Pod] Back-off restarting failed container
[node]: [Normal] [Pulled] [Pod] Container image "ghcr.io/akash-network/cosmos-omnibus:v0.3.27-bitcanna-v1.5.3" already present on machine
[node]: [Normal] [Created] [Pod] Created container node
[node]: [Normal] [Started] [Pod] Started container node
[node]: [Warning] [BackOff] [Pod] Back-off restarting failed container
[node]: [Warning] [BackOff] [Pod] Back-off restarting failed container
[node]: [Normal] [Pulled] [Pod] Container image "ghcr.io/akash-network/cosmos-omnibus:v0.3.27-bitcanna-v1.5.3" already present on machine
[node]: [Normal] [Created] [Pod] Created container node
[node]: [Normal] [Started] [Pod] Started container node
[node]: [Warning] [BackOff] [Pod] Back-off restarting failed container
[node]: [Warning] [BackOff] [Pod] Back-off restarting failed container`

And these are the logs 

`2:03PM INF ABCI Replay Blocks appHeight=8082400 module=consensus stateHeight=8082400 storeHeight=8082401
2:03PM INF Replay last block using real app module=consensus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x154660d]`

As Andy noticed, the current version of Bitcanna is 1.6.3 and the image being pulled is version 1.5.3, this might be the reason for crashing.

Another issue not directly related to this is that when using persistent storage the default ephemeral storage amount is 100 Mi, this produces another error:
`[node]: [Warning] [Evicted] [Pod] Pod ephemeral local storage usage exceeds the total limit of containers 104857600.`
Increasing ephemeral storage to 500Mi solves this error.

I suggest increasing the default amount of ephemeral storage when persistent storage is used to 1Gi

**Comment by andy108369** [comment]
looks like the 1.5.3 version is too old.

they already have 1.6.3 (all 1.6.x are compatible as well) as per https://github.com/cosmos/chain-registry/blob/master/bitcanna/chain.json#L36-L41

https://www.mintscan.io/bitcanna/proposals

https://github.com/BitCannaGlobal/bcna/releases


so 1.5.3 needs to be bumped to 1.6.3 in https://github.com/akash-network/cosmos-omnibus/tree/master/bitcanna

and https://github.com/akash-network/cosmos-omnibus/blob/v0.3.27/.github/workflows/publish.yml#L29-L30

**Comment by tombeynon** [comment]
The Bitcanna image has just been updated to v1.6.3, could you try that @shimpa1? 

https://github.com/akash-network/cosmos-omnibus/tree/master/bitcanna

**Comment by shimpa1** [comment]
thanks @tombeynon !
The image is stable after multiple hours of running.
I will do another test with persistent storage and if that works will close the issue.
thanks!

**Comment by tombeynon** [comment]
Great news, thanks for the updates @shimpa1!

**Comment by shimpa1** [comment]
the node works as expected after >24 hrs.
thank you  @tombeynon @andy108369
