### ISSUE TITLE
lumnetwork image requires update

### ISSUE THREAD

**Issue by Moonshine-cc** [akash-network/cosmos-omnibus#484]
A chain upgrade has just occured, current daemon version is v1.4.0

**Comment by Moonshine-cc** [comment]
@CharlesJUDITH 

There is another version upgrade pending that fixes the pruning issue and huckelberry patch.

What's the correct procedure to trigger a container image upgrade or who to contact about that?

**Comment by tombeynon** [comment]
Hey @Moonshine-cc (this reply applies to your comment on #487 too). 

The repository will automatically build new images whenever a new **tag** is pushed. Usually I will created `-rc*` tags in preparation and include these in the PR description, but I might not be on top of chains I (ECO Stake) don't validate. In this instance I would advise using your own fork of the repository, and pushing a tag to your fork instead. This should create images in your own account which you can use for your own validators, just make sure you set the package to public so the images can be downloaded.

**Comment by Moonshine-cc** [comment]
@tombeynon Thanks for the explanation, I'll have a look once I actually make use of the LUM image myself, though I have never done something like this before.

Can you please create the tag for the upgrade to v1.4.1 in the meantime?

https://github.com/lum-network/chain/releases/tag/v1.4.1

**Comment by tombeynon** [comment]
@Moonshine-cc pre-release image is: `ghcr.io/akash-network/cosmos-omnibus:v0.3.33-rc1-lumnetwork-v1.4.1`
