### ISSUE TITLE
Update Jackal Protocol version to 2.1.0

### ISSUE THREAD

**Issue by shimpa1** [akash-network/cosmos-omnibus#579]
@tombeynon 
There was a chain update:
https://github.com/JackalLabs/canine-chain/releases/tag/v2.1.0
If possible please update the image so that we can update the deployments
thank you!
Shimpa

**Comment by tombeynon** [comment]
Hey @shimpa1 see #568 - there's a pre-release image in the description you can use until a new release is built

**Comment by shimpa1** [comment]
awesome thank you!
