### ISSUE TITLE
canto 5.0.0: fail to start with error panic: unknown field "merge_fork_block" in types.ChainConfig

### ISSUE THREAD

**Issue by fanbsb** [akash-network/cosmos-omnibus#589]
I try to start the canto v5.0.0 from block 0, but fail with the following error
panic: unknown field "merge_fork_block" in types.ChainConfig

Maybe canto v6.0.0 fix it?

**Comment by fanbsb** [comment]
btw, the name space in build.yml is 
NAMESPACE: BCNAD

But on doc, it's 

ENV namespace | CANTOD

**Comment by fanbsb** [comment]
@tombeynon do you have time to take a look?
here is the canto github link https://github.com/Canto-Network/Canto/releases/tag/v6.0.0

**Comment by tombeynon** [comment]
@fanbsb I've opened a PR to fix the namespace (good catch!) and update to v6.0.0. The error you're seeing sounds more like it's an issue with syncing from 0 - you usually have to step through the right versions which is a pain, or easier restore from a snapshot like Polkachu's: https://polkachu.com/tendermint_snapshots/canto. I would suggest trying that, but we definitely need the right namespace and version first.

**Comment by fanbsb** [comment]
Thanks, tombeynon, I am able to download the image from ghcr.io/akash-network/cosmos-omnibus:v0.3.43-rc3-canto-v6.0.0, and use the snapshot from Polkachu.

You are right, sync from 0 is a pain indeed.
