### ISSUE TITLE
Decentr deployment does not start syncing.

### ISSUE THREAD

**Issue by shimpa1** [akash-network/cosmos-omnibus#645]
hi!
Trying to set up a Decentr validator using the image however after deployment it never starts syncing.
I tried multiple combinations from the default deployment to modified with seeds, genesis etc such as:
      - DECENTRD_PRUNING=custom
      - DECENTRD_PRUNING_INTERVAL=10
      - DECENTRD_PRUNING_KEEP_EVERY=0
      - DECENTRD_PRUNING_KEEP_RECENT=100
      - DECENTRD_P2P_FLUSH_THROTTLE_TIMEOUT=50ms
      - DECENTRD_CONSENSUS_DOUBLE_SIGN_CHECK_HEIGHT=10
      - GENESIS_URL=https://raw.githubusercontent.com/Decentr-net/mainnets/master/3.0/genesis.json
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/decentr/chain.json
      - DECENTRD_P2P_SEEDS=7708addcfb9d4ff394b18fbc6c016b4aaa90a10a@ares.mainnet.decentr.xyz:26656,8a3485f940c3b2b9f0dd979a16ea28de154f14dd@calliope.mainnet.decentr.xyz:26656,87490fd832f3226ac5d090f6a438d402670881d0@euterpe.mainnet.decentr.xyz:26656,3261bff0b7c16dcf6b5b8e62dd54faafbfd75415@hera.mainnet.decentr.xyz:26656,5f3cfa2e3d5ed2c2ef699c8593a3d93c902406a9@hermes.mainnet.decentr.xyz:26656,a529801b5390f56d5c280eaff4ae95b7163e385f@melpomene.mainnet.decentr.xyz:26656,385129dbe71bceff982204afa11ed7fa0ee39430@poseidon.mainnet.decentr.xyz:26656,35a934228c32ad8329ac917613a25474cc79bc08@terpsichore.mainnet.decentr.xyz:26656,0fd62bcd1de6f2e3cfc15852cdde9f3f8a7987e4@thalia.mainnet.decentr.xyz:26656,bd99693d0dbc855b0367f781fb48bf1ca6a6a58b@zeus.mainnet.decentr.xyz:26656

However it never actually starts syncing.

This is the link to the deployment using the default SDL:
https://bi92rfimq59gh1mu60mgoho15k.ingress.europlots.com/
And this is the link to the deployment with the seeds, genesis etc specified:
4272ijui1pfa3a0amfgp2ci6lo.ingress.europlots.com

The only piece of logs that might give an insight why it's refusing to sync is this:
Error in validation [36merr=[0m"wrong Block.Header.AppHash.  Expected 30976083FD5BC5BC2C2BCC608D716EEA8818210D13B6A1BDFD06A08BAD93C402, got 8A0D76F5FFDAD74DBD9934938B5A26FC9C9330914B03738BDEA337750BF132ED"

Would you please take a look? I can give you access to the deployments if need be.
Thanks!
Shimpa

**Comment by tombeynon** [comment]
You will likely need to use a snapshot or statesync, looks like these are available here: https://snapshots.mainnet.decentr.xyz/

e.g. `SNAPSHOT_URL=https://snapshots.mainnet.decentr.xyz/decentr-mainnet-3-snapshot-2023-10-17-06-51.tar.gz`

Otherwise to sync from 0 you'll need to use older versions initially, this is just a limitation of Cosmos SDK and the upgrade process.

**Comment by shimpa1** [comment]
OK yeah that worked thank you!
