### ISSUE TITLE
Akash node fails to start

### ISSUE THREAD

**Issue by shimpa1** [akash-network/cosmos-omnibus#660]
hello Tom,
It seems there's an issue with the default Akash Node SDL or image.
Whichever provider I choose the deployment fails to start with error logs:

`[node]: parse error: Invalid numeric literal at line 1, column 10`

Tested on multiple providers always the same outcome,

To reproduce all that's required is to deploy the default SDL on any provider.

Let me know if you need anything further!

thank you!

**Comment by ourlink** [comment]
BTW - it is not just the AKASH node that fails. We tried using the COMDEX Node and SENTINEL node and they all fail with the same error. In addition, we tried using the docker compose file and running locally, same result.

**Comment by tombeynon** [comment]
Hey @shimpa1 @ourlink this is due to the changes to Polkachu's API (#651). It will be fixed ASAP, but in the meantime you can remove P2P_POLKACHU and STATESYNC_POLKACHU env vars to avoid the error

**Comment by ourlink** [comment]
Okay great! I'll give that a try.

**Comment by shimpa1** [comment]
thank you!
