### ISSUE TITLE
Jackal node v4.1.0 is out, please update

### ISSUE THREAD

**Issue by shimpa1** [akash-network/cosmos-omnibus#886]
hi,
As the title says, the Jackal node v4.1.0 is out. v4.1.1 will be out soon as well.
https://github.com/JackalLabs/canine-chain
Please update the image thanks,
Shimpa

**Comment by tombeynon** [comment]
See the pre-release here: https://github.com/akash-network/cosmos-omnibus/pull/885

v4.1.1 will also be added before it's required
